version: "3.9"

services:
  configserver:
    image: "stallion49/config-server:v2"
    container_name: configserver
    ports:
      - "8071:8071"
    networks:
      - project
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 700m

  eurekaserver:
    image: "stallion49/eurekaserver:v2"
    container_name: eurekaserver
    ports:
      - "8070:8070"
    networks:
      - project
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      configserver:
          condition: service_healthy
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_APPLICATION_NAME: "eurekaserver"
      SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS: 6
#      SPRING_CLOUD_CONFIG_FAIL_FAST: true
      SPRING_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: DEBUG
      SPRING_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_CONFIG: DEBUG
  crypto:
    image: "stallion49/crypto:v2"
    container_name: crypto
    ports:
      - "8080:8080"
    networks:
      - project
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_APPLICATION_NAME: "crypto"
      SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS: 6
#      SPRING_CLOUD_CONFIG_FAIL_FAST: true
      SPRING_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: DEBUG
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  exchange:
    image: "stallion49/exchange:v2"
    container_name: exchange
    ports:
      - "8078:8078"
    networks:
      - project
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_APPLICATION_NAME: "exchange"
      SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS: 6
      #      SPRING_CLOUD_CONFIG_FAIL_FAST: true
      SPRING_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: DEBUG
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
  gateway:
    image: "stallion49/gateway:v2"
    container_name: gateway
    ports:
      - "8072:8072"
    networks:
      - project
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      exchange:
        condition: service_healthy
      crypto:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_APPLICATION_NAME: "gateway"
      SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS: 6
      #      SPRING_CLOUD_CONFIG_FAIL_FAST: true
      SPRING_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: DEBUG
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
networks:
  project:
    driver: "bridge"
